spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Smm6363693
  mvc:
    view:
      suffix: .html
      prefix: /templates/

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  resources:
    chain:
      cache: false


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

server:
  tomcat:
    uri-encoding: UTF-8
